name: "nerima"
version: "1.0.0"

profile: "nerima"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros", "shared/macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nerima:
    +database: nerima
    population:
      raw:
        +materialized: table
      stg:
        +materialized: view
      mart:
        +materialized: view
    bosai:
      raw:
        +materialized: table
      stg:
        +materialized: view
      mart:
        +materialized: view
    meta:
      raw:
        +materialized: table
      mart:
        +materialized: view
